version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: university_postgres
    environment:
      POSTGRES_DB: university_db
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: